In [1]:
import numpy
numpy.__version__

'1.19.2'

In [19]:
#Creating 1D Array
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr)
print(arr.ndim,"is the dimention of the array")

[1 2 3 4 5 6 7]
1 is the dimention of the array


In [3]:
type(arr)

numpy.ndarray

In [18]:
#Creating 2D Array
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[8,6,7]])
print(arr)

print(arr.ndim,"is the dimention of the array")

[[1 2 3]
 [4 5 6]
 [8 6 7]]
2 is the dimention of the array


In [20]:
#Creating 3D Array
import numpy as np
arr=np.array([[[1,2,3],[1,2,3]],
             [[7,8,5],[13,22,33]],
             [[14,25,36],[16,524,33]]])
print(arr)
print(arr.ndim,"is the dimention of the array")

[[[  1   2   3]
  [  1   2   3]]

 [[  7   8   5]
  [ 13  22  33]]

 [[ 14  25  36]
  [ 16 524  33]]]
3 is the dimention of the array


In [25]:
import numpy as np
x=np.array([1,55,77,655,44,3,2])
print(x[0],"is the x[0] element of array which is first element")
print(x[1],"is the x[1] element of array which is second element")
print(x[2],"is the x[2] element of array which is third element")
print(x[3],"is the x[3] element of array which is fourth element")
print(x[4],"is the x[4] element of array which is fifth element")
print(x[-1],"is the x[-1] element of array which is last element")
print(x[-2],"is the x[-2] element of array which is second-last element")
print(x[-3],"is the x[-3] element of array which is third-last element")
print(x[-4],"is the x[-4] element of array which is fourth-last element")

1 is the x[0] element of array which is first element
55 is the x[1] element of array which is second element
77 is the x[2] element of array which is third element
655 is the x[3] element of array which is fourth element
44 is the x[4] element of array which is fifth element
2 is the x[-1] element of array which is last element
3 is the x[-2] element of array which is second-last element
44 is the x[-3] element of array which is third-last element
655 is the x[-4] element of array which is fourth-last element


In [31]:
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [12,14,16,18],
              [21,23,25,27]])
print(arr[-2,-4])

12


In [33]:
import numpy as np
arr=np.array([1,4,5,6,7,8,6])
print(arr[0:3])
print(arr[2:])
print(arr[:3])
print(arr[0:1:-1])
print(arr[0:2:5])
print(arr[:1:4])
print(arr[0::5])
print(arr[::])

[1 4 5]
[5 6 7 8 6]
[1 4 5]
[]
[1]
[1]
[1 8]
[1 4 5 6 7 8 6]


In [34]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(x[0:2,2])

[3 8]
