In [2]:
#Method_1  All elements are converted into one data type.

import numpy as np
x=np.array([2,3,4,5])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[2 3 4 5]


In [3]:
import numpy as np
x=np.array([2,3,'n',5])
print(x)

['2' '3' 'n' '5']


In [6]:
# Method_2 Returns Equally Spaced Numbers
import numpy as np
b=np.linspace(start=1, stop=5, num=10, endpoint=True , retstep=False)
print(b)

c=np.linspace(start=1, stop=5, num=10, endpoint=True , retstep=True)
print(c)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


In [7]:
#Method_3
import numpy as np
d=np.arange(start=1,stop=10, step=2)
print(d)

[1 3 5 7 9]


In [8]:
#Method_4 returns an array with given ahape containing ones
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#Method_5 returns an array with given ahape containing zeroes
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#Method_6 Creates Random Numbers
import numpy as np
np.random.rand(5)
np.random.rand(5,2)
np.random.randint(low=1, high=100,size=4)

array([65, 14, 59, 77])

In [15]:
import numpy as np
np.random.rand(5)
np.random.rand(5,2)


array([[0.80918872, 0.30929002],
       [0.66823308, 0.95213325],
       [0.62529665, 0.98013182],
       [0.45620052, 0.34137047],
       [0.54091163, 0.31724479]])

In [16]:
import numpy as np
np.random.rand(5)

array([0.80536125, 0.58948528, 0.56679559, 0.23984781, 0.73297988])

In [17]:
import numpy as np
np.logspace(1,10,num=5, endpoint=True, base=10.0)


array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [19]:
#Method_8 recasts an array to new shape without changing data
import numpy as np
grid=np.arange(start=1,stop=10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#Method_9 Reurn dimenstions
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [23]:
#Numpy Operations
#method_10 Returns Sum
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
np.sum(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [24]:
import numpy as np
a.sum()

45

In [27]:
import numpy as np
np.sum(a,axis=0)


array([12, 15, 18])

In [41]:
import numpy as np
np.sum(a,axis=1)

array([ 6, 15, 24])

In [45]:
#method_11 Performs addition between two arrays
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.arange(start=11,stop=20).reshape(3,3)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
import numpy as np
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [47]:
import numpy as np
np.add(a,b)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [48]:
import numpy as np
np.multiply(a,b)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [50]:
import numpy as np
np.subtract(a,b)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [51]:
import numpy as np
np.divide(a,b)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [52]:
import numpy as np
np.remainder(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [53]:
import numpy as np
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
#Method_13 Performs Tranbspose of matrix
import numpy as np
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
#method_14 Appends Row to matrix
import numpy as np
a_row=np.append(a,[[10,11,14]],axis=0)
print(a_row)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 14]]


In [56]:
import numpy as np
y=np.array([11,22,33]).reshape(3,1)
print(y)

[[11]
 [22]
 [33]]


In [39]:
import numpy as np
z=np.append(y,[[1,2,3],[4,5,6],[7,8,9]],axis=1)

In [62]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a_new=np.insert(a,1,[[10,11,12]],axis=0)
print(a_new)


[[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


In [57]:
# Deletes Row
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a_new=np.delete(a,1,axis=0)
print(a_new)

[[1 2 3]
 [7 8 9]]


In [58]:
a=np.matrix("1,2,3;4,5,6;7,8,9")
print(a)
print(a.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [59]:
a=np.matrix("1,2,3;4,5,6;7,8,9;10,11,12")
print(a)
print(a.shape)
print('')
print(a.shape[0])
print(a.shape[1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)

4
3


In [60]:
a=np.matrix("1,2,3;4,5,6;7,8,9;10,11,12")
col_new=np.matrix("13,14,15")
print(col_new)
a=np.insert(a,0 ,col_new,axis=0)
print(a)

[[13 14 15]]
[[13 14 15]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [61]:
a=np.matrix("1,2,3;4,5,6;7,8,9;10,11,12")
print(a.size)

12


In [65]:
#Method_20  Adds values at a given position and axis in a matrix
a=np.matrix("1,2,3;4,5,6;7,8,9;10,11,12")
col_new=np.matrix("13,14,15")
print(col_new)
a=np.insert(a,0 ,col_new,axis=0)
print(a)

[[13 14 15]]
[[13 14 15]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [66]:
# Method 21:Elementwise Addition
a=np.matrix(np.arange(0,20)).reshape(5,4)
b=np.matrix(np.arange(20,40)).reshape(5,4)
print(np.add(a,b))

[[20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]
 [44 46 48 50]
 [52 54 56 58]]


In [67]:
# Method 22: Elementwise Substraction
a=np.matrix(np.arange(0,20)).reshape(5,4)
b=np.matrix(np.arange(20,40)).reshape(5,4)
print(np.subtract(a,b))

[[-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]]


In [68]:
# Method 23: Performs elementwise multiplication
a=np.matrix(np.arange(0,20)).reshape(5,4)
b=np.matrix(np.arange(20,40)).reshape(5,4)
print(np.multiply(a,b))

[[  0  21  44  69]
 [ 96 125 156 189]
 [224 261 300 341]
 [384 429 476 525]
 [576 629 684 741]]


In [69]:
# Method 24: Matrix multiplication between matrices
a=np.matrix(np.arange(0,20)).reshape(5,4)
b=np.matrix(np.arange(20,40)).reshape(5,4)
b=np.transpose(b)
print(np.dot(a,b))

[[ 134  158  182  206  230]
 [ 478  566  654  742  830]
 [ 822  974 1126 1278 1430]
 [1166 1382 1598 1814 2030]
 [1510 1790 2070 2350 2630]]


In [70]:
# Method 25: Performs Elementwise division between two matrix
a=np.matrix(np.arange(0,20)).reshape(5,4)
b=np.matrix(np.arange(20,40)).reshape(5,4)
print(np.divide(a,b))

[[0.         0.04761905 0.09090909 0.13043478]
 [0.16666667 0.2        0.23076923 0.25925926]
 [0.28571429 0.31034483 0.33333333 0.35483871]
 [0.375      0.39393939 0.41176471 0.42857143]
 [0.44444444 0.45945946 0.47368421 0.48717949]]


In [71]:
# Method 27 :
a=np.matrix("1,2,3;4,5,6;7,8,9;10,11,12")
rank_a=np.linalg.matrix_rank(a)
print(rank_a)

2


In [74]:
#Method_26  Returns Determinant
x=np.matrix("4,5,16,7;2,-3,2,3;3,4,5,6;4,7,8,9")
print(x)
det_matrix=np.linalg.det(x)
print(det_matrix)

[[ 4  5 16  7]
 [ 2 -3  2  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]
128.00000000000009


In [79]:
#Method_29 Return Solution of Ax=b
A=np.matrix("3,1,2;3,2,5;6,7,8")

print(A)


[[3 1 2]
 [3 2 5]
 [6 7 8]]


In [80]:
b=np.matrix("2,-1,3").transpose()
print(b)

[[ 2]
 [-1]
 [ 3]]


In [81]:
sol_linear=np.linalg.solve(A,b)
print(sol_linear)

[[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]


In [82]:
# Method 28 : returns the multiplicative inverse of a matrix
a=np.matrix("3,1,2;3,2,5;6,7,8")
inv_a=np.linalg.inv(a)
print(inv_a)


[[ 0.57575758 -0.18181818 -0.03030303]
 [-0.18181818 -0.36363636  0.27272727]
 [-0.27272727  0.45454545 -0.09090909]]
